gym_project_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: datalab
      schema: silver # Aquí es donde dbt creará tus tablas limpias
      threads: 4
